// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/Atoms/AddButton.vue')['default']
    AddButtonExtend: typeof import('./src/components/Atoms/AddButtonExtend.vue')['default']
    CountNumber: typeof import('./src/components/CountNumber.vue')['default']
    CountNumberExtend: typeof import('./src/components/CountNumberExtend.vue')['default']
    PlayGound: typeof import('./src/components/Atoms/PlayGound.vue')['default']
    PlayGoundExtend: typeof import('./src/components/Atoms/PlayGoundExtend.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VContent: typeof import('vuetify/lib')['VContent']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VLayout: typeof import('vuetify/lib')['VLayout']
    VMain: typeof import('vuetify/lib')['VMain']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export {}
